"""Descriptive statistics for the barren-plateau dataset -> LaTeX tables.

Emits three booktabs table fragments used by the paper's Data Description section:
  * table_designspace.tex  -- the sampled design space (features, type, values)
  * table_datastats.tex     -- per-feature descriptive statistics + the label
  * table_labelbydesign.tex -- trainability broken down by design choice
                               (this is where the data reproduces BP theory)

    python -m qml_bp.describe_data --data data_bp/bp_dataset.csv --outdir paper/latex
"""

import argparse
import os

import numpy as np
import pandas as pd

from qml_bp.ansatz import ENTANGLE_PATTERNS, ENTANGLER_GATES

BARREN = -2.0  # log10(var) threshold


def _fmt(x, nd=2):
    return ("%%.%df" % nd) % x


def design_space(df, path):
    rows = [
        ("\\texttt{n\\_qubits}", "integer", "%d--%d" % (df.n_qubits.min(), df.n_qubits.max())),
        ("\\texttt{n\\_layers}", "integer", "%d--%d" % (df.n_layers.min(), df.n_layers.max())),
        ("\\texttt{ansatz\\_type}", "categorical (2)", "fixed-\\texttt{ry}, random-Pauli"),
        ("\\texttt{entangle\\_pattern}", "categorical (3)", "linear, circular, all-to-all"),
        ("\\texttt{entangler\\_gate}", "categorical (2)", "CZ, CX"),
        ("\\texttt{cost\\_global}", "binary", "local $Z_0$, global $Z^{\\otimes n}$"),
    ]
    lines = [
        "% Auto-generated by qml_bp/describe_data.py -- do not edit.",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "\\textbf{Design parameter} & \\textbf{Type} & \\textbf{Sampled values}\\\\",
        "\\midrule",
    ]
    for name, typ, vals in rows:
        lines.append("%s & %s & %s\\\\" % (name, typ, vals))
    lines += ["\\bottomrule", "\\end{tabular}"]
    _write(path, lines)


def data_stats(df, path):
    cols = ["n_qubits", "n_layers", "n_params", "n_entanglers", "depth_ratio",
            "log_grad_var"]
    nice = {
        "n_qubits": "\\texttt{n\\_qubits}", "n_layers": "\\texttt{n\\_layers}",
        "n_params": "\\texttt{n\\_params}", "n_entanglers": "\\texttt{n\\_entanglers}",
        "depth_ratio": "\\texttt{depth\\_ratio}",
        "log_grad_var": "$\\log_{10}\\mathrm{Var}$ (label)",
    }
    lines = [
        "% Auto-generated by qml_bp/describe_data.py -- do not edit.",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "\\textbf{Variable} & \\textbf{Mean} & \\textbf{Std} & \\textbf{Min} "
        "& \\textbf{25\\%} & \\textbf{Median} & \\textbf{Max}\\\\",
        "\\midrule",
    ]
    for c in cols:
        s = df[c]
        nd = 2
        lines.append("%s & %s & %s & %s & %s & %s & %s\\\\" % (
            nice[c], _fmt(s.mean(), nd), _fmt(s.std(), nd), _fmt(s.min(), nd),
            _fmt(s.quantile(.25), nd), _fmt(s.median(), nd), _fmt(s.max(), nd)))
    lines += ["\\bottomrule", "\\end{tabular}"]
    _write(path, lines)


def label_by_design(df, path):
    """Mean log-variance and barren fraction grouped by each design choice."""
    df = df.copy()
    df["barren"] = (df.log_grad_var < BARREN).astype(int)

    def rows(col, labels):
        out = []
        for i, lab in enumerate(labels):
            sub = df[df[col] == i]
            if len(sub) == 0:
                continue
            out.append("\\quad %s & %d & %s & %s\\\\" % (
                lab, len(sub), _fmt(sub.log_grad_var.mean(), 2),
                _fmt(100 * sub.barren.mean(), 1)))
        return out

    groups = [
        ("Cost-observable locality", "cost_global",
         ["local $Z_0$", "global $Z^{\\otimes n}$"]),
        ("Entanglement pattern", "entangle_pattern",
         [p.replace("_", "-") for p in ENTANGLE_PATTERNS]),
        ("Entangler gate", "entangler_gate", [g.upper() for g in ENTANGLER_GATES]),
        ("Single-qubit rotation scheme", "ansatz_type",
         ["fixed-\\texttt{ry}", "random-Pauli"]),
    ]
    lines = [
        "% Auto-generated by qml_bp/describe_data.py -- do not edit.",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "\\textbf{Design choice} & \\textbf{Count} "
        "& \\textbf{Mean} $\\boldsymbol{\\log_{10}\\mathrm{Var}}$ "
        "& \\textbf{Barren \\%}\\\\",
        "\\midrule",
    ]
    for gi, (title, col, labels) in enumerate(groups):
        if gi:
            lines.append("\\midrule")
        lines.append("\\multicolumn{4}{l}{\\emph{%s}}\\\\" % title)
        lines += rows(col, labels)
    lines += ["\\bottomrule", "\\end{tabular}"]
    _write(path, lines)


def _write(path, lines):
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("Wrote", path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--outdir", default="paper/latex")
    args = ap.parse_args()
    df = pd.read_csv(args.data)
    print("Loaded %d rows" % len(df))
    design_space(df, os.path.join(args.outdir, "table_designspace.tex"))
    data_stats(df, os.path.join(args.outdir, "table_datastats.tex"))
    label_by_design(df, os.path.join(args.outdir, "table_labelbydesign.tex"))

    # console summary
    df2 = df.copy()
    df2["barren"] = (df2.log_grad_var < BARREN).astype(int)
    print("\nLabel by cost locality:")
    print(df2.groupby("cost_global").agg(
        n=("log_grad_var", "size"),
        mean_logvar=("log_grad_var", "mean"),
        barren_pct=("barren", "mean")))


if __name__ == "__main__":
    main()
